import { createElement } from 'lwc';  // Assurez-vous d'importer createElement
import MyLWC from 'c/myLWC';           // Assurez-vous que le chemin est correct

describe('c-my-lwc', () => {
    afterEach(() => {
        // Reset the DOM after each test
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-my-lwc', {
            is: MyLWC
        });

        // Act
        document.body.appendChild(element);

        // Assert
        const div = element.shadowRoot.querySelector('div');
        expect(div).not.toBeNull();  // Vérifie que le div existe
    });
});
